name = "ChipFiring"
uuid = "be096eff-6f16-4fe8-bf2d-b0d7a78a4be0"
authors = ["Vincent Wang <vincentxwang@uchicago.edu>"]
version = "0.4.1"

[deps]
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"

[compat]
Graphs = "1.9.0"
julia = "1.10"
